# Generated by Django 3.2.7 on 2021-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=90)),
                ('pin_code', models.CharField(max_length=70)),
            ],
        ),
    ]
