# Generated by Django 3.2.7 on 2021-09-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210922_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip_code',
            new_name='pin_code',
        ),
    ]
