# Generated by Django 3.2.7 on 2021-09-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_orders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='pin_code',
        ),
    ]
